site_name: Automação
theme:
  name: material
  language: pt-BR
plugins:
- search
- mkdocstrings:
    handlers:
      python: 
        options:  
          heading_level: 0 # 0 Elimina a duplicidade de nomes na lista de conteúdo


